# Julia Basics

Let's have a test if the IJulia Kernel works first.

In [106]:
print("Hello")

Hello

In [107]:
using LinearAlgebra
norm(rand(1,2))

0.8559083934734684

## Basic Data Type

In [108]:
a = 1.1 + 0.1 - 1.2
b = 1.1 - 1.2 + 0.1
a ≈ b

false

In [109]:
a + 1 ≈ b + 1

true

In [134]:
?≈

"≈" can be typed by \approx<tab>

search: ≈



```
isapprox(x, y; atol::Real=0, rtol::Real=atol>0 ? 0 : √eps, nans::Bool=false[, norm::Function])
```

Inexact equality comparison: `true` if `norm(x-y) <= max(atol, rtol*max(norm(x), norm(y)))`. The default `atol` is zero and the default `rtol` depends on the types of `x` and `y`. The keyword argument `nans` determines whether or not NaN values are considered equal (defaults to false).

For real or complex floating-point values, if an `atol > 0` is not specified, `rtol` defaults to the square root of [`eps`](@ref) of the type of `x` or `y`, whichever is bigger (least precise). This corresponds to requiring equality of about half of the significand digits. Otherwise, e.g. for integer arguments or if an `atol > 0` is supplied, `rtol` defaults to zero.

The `norm` keyword defaults to `abs` for numeric `(x,y)` and to `LinearAlgebra.norm` for arrays (where an alternative `norm` choice is sometimes useful). When `x` and `y` are arrays, if `norm(x-y)` is not finite (i.e. `±Inf` or `NaN`), the comparison falls back to checking whether all elements of `x` and `y` are approximately equal component-wise.

The binary operator `≈` is equivalent to `isapprox` with the default arguments, and `x ≉ y` is equivalent to `!isapprox(x,y)`.

Note that `x ≈ 0` (i.e., comparing to zero with the default tolerances) is equivalent to `x == 0` since the default `atol` is `0`.  In such cases, you should either supply an appropriate `atol` (or use `norm(x) ≤ atol`) or rearrange your code (e.g. use `x ≈ y` rather than `x - y ≈ 0`).   It is not possible to pick a nonzero `atol` automatically because it depends on the overall scaling (the "units") of your problem: for example, in `x - y ≈ 0`, `atol=1e-9` is an absurdly small tolerance if `x` is the [radius of the Earth](https://en.wikipedia.org/wiki/Earth_radius) in meters, but an absurdly large tolerance if `x` is the [radius of a Hydrogen atom](https://en.wikipedia.org/wiki/Bohr_radius) in meters.

!!! compat "Julia 1.6"
    Passing the `norm` keyword argument when comparing numeric (non-array) arguments requires Julia 1.6 or later.


# Examples

```jldoctest
julia> 0.1 ≈ (0.1 - 1e-10)
true

julia> isapprox(10, 11; atol = 2)
true

julia> isapprox([10.0^9, 1.0], [10.0^9, 2.0])
true

julia> 1e-10 ≈ 0
false

julia> isapprox(1e-10, 0, atol=1e-8)
true
```

---

```
isapprox(x; kwargs...) / ≈(x; kwargs...)
```

Create a function that compares its argument to `x` using `≈`, i.e. a function equivalent to `y -> y ≈ x`.

The keyword arguments supported here are the same as those in the 2-argument `isapprox`.


Broadcasting

In [111]:
1 * NaN

NaN

In [112]:
1 * missing

missing

In [113]:
typeof(missing)

Missing

Missing is used in stat, but different from nothing DataType.

In [114]:
typeof(nothing)

Nothing

## @ macro

In [115]:
x = rand()

0.11255497544989379

In [116]:
@show x

x = 0.11255497544989379


0.11255497544989379

In [117]:
@info x

┌ Info: 0.11255497544989379
└ @ Main In[117]:1


In [118]:
@macroexpand @show x

quote
    Base.println("x = ", Base.repr(begin
                #= show.jl:955 =#
                local var"#91#value" = x
            end))
    var"#91#value"
end

In [119]:
@time rand(4,4)

  0.000007 seconds (1 allocation: 208 bytes)


4×4 Matrix{Float64}:
 0.799988  0.34545   0.0866386  0.520805
 0.602716  0.829578  0.0353974  0.902721
 0.477885  0.343997  0.436464   0.478827
 0.687388  0.920357  0.115371   0.436292

在Benchmark下，跑很多次，来统计时间，看起来很有用

In [120]:
using BenchmarkTools
@btime rand(4,4)

  64.365 ns (1 allocation: 208 bytes)


4×4 Matrix{Float64}:
 0.734522   0.855013  0.773875  0.932673
 0.0813174  0.203905  0.257079  0.0767134
 0.418065   0.625931  0.744806  0.26216
 0.784636   0.987793  0.828566  0.588475

In [121]:
@benchmark rand(4,4)

BenchmarkTools.Trial: 10000 samples with 985 evaluations.
 Range (min … max):   64.670 ns …  2.442 μs  ┊ GC (min … max): 0.00% … 92.05%
 Time  (median):      84.061 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   106.238 ns ± 90.454 ns  ┊ GC (mean ± σ):  4.54% ±  5.98%

  ▃▆▇█▆▅▅▄▄▄▄▃▂▂▂▂▂▁ ▁▁▁▁▁▁▁▁▁                                 ▂
  ██████████████████████████████▇▆▇▆▆▆▆▆▆▆▅▄▄▄▄▅▄▅▄▄▂▅▅▅▄▅▃▅▄▃ █
  64.7 ns       Histogram: log(frequency) by time       356 ns <

 Memory estimate: 208 bytes, allocs estimate: 1.

## 字符和字符串

In [122]:
char c = 'c'

LoadError: syntax: extra token "c" after end of expression

字符串的插值使用

In [ ]:
msg = "world"
"hello $msg"

"hello world"

In [ ]:
"hello," * "world"

"hello,world"

In [ ]:
parse(Int, "1")

1

## 内置数据类型

In [ ]:
x = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
x = [1,2,3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

比较二者可以发现Julia的强类型设置，当然下面的更泛

In [ ]:
x = Real[1,2,3]

3-element Vector{Real}:
 1
 2
 3

In [ ]:
x = Any[1,2,3]

3-element Vector{Any}:
 1
 2
 3

In [ ]:
x[1]

1

In [ ]:
x[1:end]

3-element Vector{Real}:
 1
 2
 3

In [ ]:
y = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [ ]:
x = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
x == y # 行向量和列向量是不一样的

false

However,

In [ ]:
y'

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 2
 3

In [ ]:
x == y'

false

In [ ]:
reshape(x, size(y')) == y'

true

In [ ]:
A = [1 2 3 4; 5 6 5 8]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  5  8

In [ ]:
A .* 2

2×4 Matrix{Int64}:
  2   4   6   8
 10  12  14  16

In [ ]:
inv([1 3;3 1])

2×2 Matrix{Float64}:
 -0.125   0.375
  0.375  -0.125

In [ ]:
A * [1,2,3,4]

2-element Vector{Int64}:
 30
 70

In [ ]:
[1 2 3 4
5 6 7 8]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

支持换行是因为模拟时候的一个常见操作：

In [ ]:
rand(4,4)

4×4 Matrix{Float64}:
 0.461816  0.587048  0.21194   0.249983
 0.282921  0.120471  0.372949  0.145057
 0.285329  0.650137  0.867497  0.350462
 0.61627   0.845913  0.63898   0.495546

In [ ]:
[0.461816  0.587048  0.21194   0.249983
0.282921  0.120471  0.372949  0.145057
0.285329  0.650137  0.867497  0.350462
0.61627   0.845913  0.63898   0.495546]

4×4 Matrix{Float64}:
 0.461816  0.587048  0.21194   0.249983
 0.282921  0.120471  0.372949  0.145057
 0.285329  0.650137  0.867497  0.350462
 0.61627   0.845913  0.63898   0.495546

更新的版本也有tensor

In [ ]:
x = (1,2,3) # tuple
typeof(x) # 和Matrix不同

Tuple{Int64, Int64, Int64}

In [ ]:
x,y = 1,2,3,4,5
@show x y

x = 1
y = 2


2

In [ ]:
d = Dict(
    1 => "first",
    "2" => "second",
    (3,4) => "3rd, 4rd"
)

Dict{Any, String} with 3 entries:
  "2"    => "second"
  (3, 4) => "3rd, 4rd"
  1      => "first"

In [ ]:
keys(d)

KeySet for a Dict{Any, String} with 3 entries. Keys:
  "2"
  (3, 4)
  1

## 第三方数据类型

# Function

可变参数

In [ ]:
function mysum(x, y...)
    z = copy(x)
    for i in y
        z += i
    end
end

mysum (generic function with 1 method)

位置参数 vs. 关键词参数

传参方式是refrence

In [ ]:
function change(x)
    x[1] = 0
    x
end

change (generic function with 1 method)

In [ ]:
x = [1,2,3]
change(x)
x

3-element Vector{Int64}:
 0
 2
 3

In [129]:
x = rand(1:5,10)

10-element Vector{Int64}:
 5
 1
 2
 5
 5
 5
 2
 3
 4
 2

In [130]:
using SortingAlgorithms
sort(x)
x

10-element Vector{Int64}:
 5
 1
 2
 5
 5
 5
 2
 3
 4
 2

In [131]:
sort!(x) # inplace version

10-element Vector{Int64}:
 1
 2
 2
 2
 3
 4
 5
 5
 5
 5

因此，一般写函数时都会写两个版本，一个带感叹号，一个不带。

## 函数式编程
 - 一个函数的输入可能是另一个函数
 - map, reduce, mapreduce, ...

In [136]:
map(+, 1:5, 2:6)

1:7:1

In [137]:
reduce(+, [1,2,3])

6

In [150]:
MaskA = rand(Bool, 4, 4)

4×4 Matrix{Bool}:
 0  0  0  1
 1  1  1  1
 1  0  1  1
 1  0  1  1

In [149]:
MaskB = rand(Bool, 4, 4)

4×4 Matrix{Bool}:
 1  0  1  0
 0  0  1  1
 0  0  0  0
 0  0  0  0

In [156]:
@btime MaskA .& MaskB

  436.181 ns (4 allocations: 208 bytes)


4×4 BitMatrix:
 0  0  0  0
 0  0  1  1
 0  0  0  0
 0  0  0  0

In [157]:
@btime $MaskA .& $MaskB

  92.017 ns (2 allocations: 144 bytes)


4×4 BitMatrix:
 0  0  0  0
 0  0  1  1
 0  0  0  0
 0  0  0  0

In [162]:
@benchmark $MaskA .& $MaskB

BenchmarkTools.Trial: 10000 samples with 955 evaluations.
 Range (min … max):   94.241 ns …  11.517 μs  ┊ GC (min … max):  0.00% … 98.91%
 Time  (median):     112.147 ns               ┊ GC (median):     0.00%
 Time  (mean ± σ):   150.136 ns ± 412.817 ns  ┊ GC (mean ± σ):  14.13% ±  5.26%

  ▂▄▆█▆▄▄▃▂▂▂▁▁                                                 ▁
  ██████████████▇▇▇█▆▇██▇▇▆▇▇█▇▇▇█▇▇█▇▇▇▇▇▆▆▆▇▇▆▆▅▅▅▅▆▆▅▆▄▄▃▄▄▃ █
  94.2 ns       Histogram: log(frequency) by time        372 ns <

 Memory estimate: 144 bytes, allocs estimate: 2.

Benchmark时在变量前加$，这还是在做插值，做的是把Julia的全局空间和Benchmark的局部空间隔离开。
这和类型是稳定的有关系，举个例子：

In [172]:
x = [1]
f(x) = x[1] > 0.5 ? 1.0 : 0.0
f(x::Int) = x[1]

f (generic function with 2 methods)

In [174]:
@btime f(x)

  24.197 ns (1 allocation: 16 bytes)


1.0

In [175]:
@btime f($x)

  1.500 ns (0 allocations: 0 bytes)


1.0

这个原因和Julia全局变量是类型不稳定的有关。

In [161]:
@btime map(&, $MaskA, $MaskB)

  54.010 ns (1 allocation: 112 bytes)


4×4 Matrix{Bool}:
 0  0  0  0
 0  0  1  1
 0  0  0  0
 0  0  0  0

## 没有类编程

原因是类编程会使生态割裂，多重派发从原理上更优越。